// Mock data for development - will be replaced by Prisma queries
export const BRANDS = [
  {
    id: "1",
    name: "Rolex",
    slug: "rolex",
    logo: "/brands/rolex.png",
    description: "Vương giả của thế giới đồng hồ, biểu tượng của sự thành công và đẳng cấp từ năm 1905.",
    country: "Thụy Sĩ",
    foundedYear: 1905,
  },
  {
    id: "2",
    name: "Patek Philippe",
    slug: "patek-philippe",
    logo: "/brands/patek.png",
    description: "Kiệt tác thời gian được truyền qua nhiều thế hệ. Bạn không bao giờ thực sự sở hữu một chiếc Patek Philippe, bạn chỉ giữ nó cho thế hệ tiếp theo.",
    country: "Thụy Sĩ",
    foundedYear: 1839,
  },
  {
    id: "3",
    name: "Audemars Piguet",
    slug: "audemars-piguet",
    logo: "/brands/ap.png",
    description: "Nghệ thuật chế tác đồng hồ cao cấp từ thung lũng Joux, nổi tiếng với Royal Oak huyền thoại.",
    country: "Thụy Sĩ",
    foundedYear: 1875,
  },
  {
    id: "4",
    name: "Omega",
    slug: "omega",
    logo: "/brands/omega.png",
    description: "Đồng hồ chính thức của NASA và Olympic, biểu tượng của sự chính xác và phiêu lưu.",
    country: "Thụy Sĩ",
    foundedYear: 1848,
  },
  {
    id: "5",
    name: "IWC Schaffhausen",
    slug: "iwc",
    logo: "/brands/iwc.png",
    description: "Kỹ thuật Thụy Sĩ kết hợp tinh thần thiết kế, nổi tiếng với dòng Pilot's Watch và Portugieser.",
    country: "Thụy Sĩ",
    foundedYear: 1868,
  },
  {
    id: "6",
    name: "Cartier",
    slug: "cartier",
    logo: "/brands/cartier.png",
    description: "Vua của đồ trang sức, hoàng đế của đồng hồ. Cartier định nghĩa sự thanh lịch từ 1847.",
    country: "Pháp",
    foundedYear: 1847,
  },
  {
    id: "7",
    name: "Vacheron Constantin",
    slug: "vacheron-constantin",
    logo: "/brands/vacheron.png",
    description: "Nhà sản xuất đồng hồ lâu đời nhất thế giới hoạt động liên tục từ 1755.",
    country: "Thụy Sĩ",
    foundedYear: 1755,
  },
  {
    id: "8",
    name: "Jaeger-LeCoultre",
    slug: "jaeger-lecoultre",
    logo: "/brands/jlc.png",
    description: "Nhà phát minh của thung lũng Joux, sáng tạo hơn 1,200 calibre khác nhau.",
    country: "Thụy Sĩ",
    foundedYear: 1833,
  },
];

export const CATEGORIES = [
  { id: "1", name: "Đồng Hồ Nam", slug: "dong-ho-nam", image: "/categories/men.jpg" },
  { id: "2", name: "Đồng Hồ Nữ", slug: "dong-ho-nu", image: "/categories/women.jpg" },
  { id: "3", name: "Đồng Hồ Đôi", slug: "dong-ho-doi", image: "/categories/couple.jpg" },
  { id: "4", name: "Đồng Hồ Thể Thao", slug: "dong-ho-the-thao", image: "/categories/sport.jpg" },
  { id: "5", name: "Đồng Hồ Cổ Điển", slug: "dong-ho-co-dien", image: "/categories/classic.jpg" },
  { id: "6", name: "Đồng Hồ Lặn", slug: "dong-ho-lan", image: "/categories/diver.jpg" },
];

export const WATCHES = [
  {
    id: "1",
    sku: "RLX-SUB-001",
    name: "Rolex Submariner Date 41mm",
    slug: "rolex-submariner-date-41mm",
    price: 285000000,
    originalPrice: 310000000,
    stock: 3,
    soldCount: 47,
    isFeatured: true,
    isLimited: false,
    images: [
      "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800",
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800",
    ],
    movement: "Automatic",
    caseMaterial: "Oystersteel",
    dialColor: "Đen",
    waterResistance: "30 ATM",
    caseSize: "41mm",
    strapMaterial: "Thép Oyster",
    warranty: 5,
    brandId: "1",
    categoryId: "1",
    brand: { name: "Rolex", slug: "rolex" },
    category: { name: "Đồng Hồ Nam", slug: "dong-ho-nam" },
    badge: "Best Seller",
    description: "Rolex Submariner Date, chiếc đồng hồ lặn huyền thoại với vành bezel xoay Cerachrom và bộ máy Calibre 3235 tự động lên dây cót. Chống nước 300m, tinh thể sapphire chống xước.",
  },
  {
    id: "2",
    sku: "PP-NAU-001",
    name: "Patek Philippe Nautilus 5711",
    slug: "patek-philippe-nautilus-5711",
    price: 1250000000,
    originalPrice: null,
    stock: 1,
    soldCount: 12,
    isFeatured: true,
    isLimited: true,
    images: [
      "https://images.unsplash.com/photo-1548171916-c8d1c1e8bc66?w=800",
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800",
    ],
    movement: "Automatic",
    caseMaterial: "Vàng Trắng 18K",
    dialColor: "Xanh Navy",
    waterResistance: "12 ATM",
    caseSize: "40mm",
    strapMaterial: "Vàng Trắng 18K",
    warranty: 2,
    brandId: "2",
    categoryId: "1",
    brand: { name: "Patek Philippe", slug: "patek-philippe" },
    category: { name: "Đồng Hồ Nam", slug: "dong-ho-nam" },
    badge: "Limited Edition",
    description: "Patek Philippe Nautilus 5711/1A - biểu tượng của sự sang trọng thể thao. Thiết kế bởi Gérald Genta năm 1976, trở thành một trong những chiếc đồng hồ được săn đón nhất thế giới.",
  },
  {
    id: "3",
    sku: "AP-RO-001",
    name: "Audemars Piguet Royal Oak 41mm",
    slug: "audemars-piguet-royal-oak-41mm",
    price: 890000000,
    originalPrice: 950000000,
    stock: 2,
    soldCount: 28,
    isFeatured: true,
    isLimited: false,
    images: [
      "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?w=800",
      "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800",
    ],
    movement: "Automatic",
    caseMaterial: "Thép không gỉ",
    dialColor: "Grande Tapisserie Xanh",
    waterResistance: "5 ATM",
    caseSize: "41mm",
    strapMaterial: "Thép không gỉ",
    warranty: 5,
    brandId: "3",
    categoryId: "1",
    brand: { name: "Audemars Piguet", slug: "audemars-piguet" },
    category: { name: "Đồng Hồ Nam", slug: "dong-ho-nam" },
    badge: "New Arrival",
    description: "Royal Oak 'Jumbo' Extra-Thin - kiệt tác của Gérald Genta với vỏ bát giác và ốc vít lộ. Bộ máy Calibre 4302 tự động, dự trữ năng lượng 70 giờ.",
  },
  {
    id: "4",
    sku: "OMG-SPM-001",
    name: "Omega Speedmaster Moonwatch Professional",
    slug: "omega-speedmaster-moonwatch-professional",
    price: 165000000,
    originalPrice: 185000000,
    stock: 5,
    soldCount: 63,
    isFeatured: true,
    isLimited: false,
    images: [
      "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=800",
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800",
    ],
    movement: "Manual",
    caseMaterial: "Thép không gỉ",
    dialColor: "Đen",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapMaterial: "Thép không gỉ",
    warranty: 5,
    brandId: "4",
    categoryId: "4",
    brand: { name: "Omega", slug: "omega" },
    category: { name: "Đồng Hồ Thể Thao", slug: "dong-ho-the-thao" },
    badge: "Best Seller",
    description: "Chiếc đồng hồ đầu tiên lên Mặt Trăng. Omega Speedmaster Professional Moonwatch với bộ máy chronograph thủ công Calibre 321, kính Hesalite huyền thoại.",
  },
  {
    id: "5",
    sku: "IWC-POR-001",
    name: "IWC Portugieser Chronograph",
    slug: "iwc-portugieser-chronograph",
    price: 198000000,
    originalPrice: null,
    stock: 4,
    soldCount: 35,
    isFeatured: false,
    isLimited: false,
    images: [
      "https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800",
      "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800",
    ],
    movement: "Automatic",
    caseMaterial: "Thép không gỉ",
    dialColor: "Trắng Bạc",
    waterResistance: "3 ATM",
    caseSize: "41mm",
    strapMaterial: "Da cá sấu",
    warranty: 2,
    brandId: "5",
    categoryId: "5",
    brand: { name: "IWC Schaffhausen", slug: "iwc" },
    category: { name: "Đồng Hồ Cổ Điển", slug: "dong-ho-co-dien" },
    badge: null,
    description: "IWC Portugieser Chronograph - thiết kế thanh lịch vượt thời gian với bộ máy chronograph tự động Calibre 69355, dự trữ năng lượng 46 giờ.",
  },
  {
    id: "6",
    sku: "CTR-SNT-001",
    name: "Cartier Santos de Cartier Medium",
    slug: "cartier-santos-medium",
    price: 215000000,
    originalPrice: 235000000,
    stock: 3,
    soldCount: 41,
    isFeatured: true,
    isLimited: false,
    images: [
      "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800",
      "https://images.unsplash.com/photo-1639037687537-1f12e2a5e1c6?w=800",
    ],
    movement: "Automatic",
    caseMaterial: "Thép & Vàng Hồng 18K",
    dialColor: "Trắng Bạc",
    waterResistance: "10 ATM",
    caseSize: "35.1mm",
    strapMaterial: "Thép & Vàng Hồng 18K",
    warranty: 2,
    brandId: "6",
    categoryId: "2",
    brand: { name: "Cartier", slug: "cartier" },
    category: { name: "Đồng Hồ Nữ", slug: "dong-ho-nu" },
    badge: "Sale",
    description: "Santos de Cartier - chiếc đồng hồ đeo tay đầu tiên trong lịch sử, thiết kế bởi Louis Cartier năm 1904 cho phi công Alberto Santos-Dumont. Hệ thống QuickSwitch thay dây nhanh.",
  },
  {
    id: "7",
    sku: "VC-PAT-001",
    name: "Vacheron Constantin Patrimony",
    slug: "vacheron-constantin-patrimony",
    price: 720000000,
    originalPrice: null,
    stock: 1,
    soldCount: 8,
    isFeatured: true,
    isLimited: true,
    images: [
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800",
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800",
    ],
    movement: "Manual",
    caseMaterial: "Vàng Hồng 18K",
    dialColor: "Bạc Opaline",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapMaterial: "Da cá sấu Mississippi",
    warranty: 2,
    brandId: "7",
    categoryId: "5",
    brand: { name: "Vacheron Constantin", slug: "vacheron-constantin" },
    category: { name: "Đồng Hồ Cổ Điển", slug: "dong-ho-co-dien" },
    badge: "Limited Edition",
    description: "Vacheron Constantin Patrimony - sự tinh khiết tuyệt đối trong thiết kế đồng hồ. Mặt số tối giản, vỏ vàng hồng 18K siêu mỏng với bộ máy Calibre 1400.",
  },
  {
    id: "8",
    sku: "JLC-REV-001",
    name: "Jaeger-LeCoultre Reverso Classic",
    slug: "jaeger-lecoultre-reverso-classic",
    price: 245000000,
    originalPrice: 268000000,
    stock: 4,
    soldCount: 22,
    isFeatured: false,
    isLimited: false,
    images: [
      "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800",
      "https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800",
    ],
    movement: "Manual",
    caseMaterial: "Thép không gỉ",
    dialColor: "Trắng Bạc",
    waterResistance: "3 ATM",
    caseSize: "45.6 x 27.4mm",
    strapMaterial: "Da cá sấu",
    warranty: 8,
    brandId: "8",
    categoryId: "5",
    brand: { name: "Jaeger-LeCoultre", slug: "jaeger-lecoultre" },
    category: { name: "Đồng Hồ Cổ Điển", slug: "dong-ho-co-dien" },
    badge: "Sale",
    description: "Jaeger-LeCoultre Reverso - thiết kế lật mặt huyền thoại ra đời năm 1931 cho các tay chơi polo. Bộ máy thủ công Calibre 822/2, có thể khắc chữ mặt sau.",
  },
];

export const BLOGS = [
  {
    id: "1",
    title: "Lịch Sử Huyền Thoại Rolex: Từ London Đến Đỉnh Cao Thế Giới",
    slug: "lich-su-huyen-thoai-rolex",
    excerpt: "Khám phá hành trình từ một xưởng nhỏ ở London đến đế chế đồng hồ lớn nhất thế giới. Câu chuyện về Hans Wilsdorf và tầm nhìn cách mạng.",
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800",
    views: 12500,
    isPublished: true,
    createdAt: "2025-11-15",
    author: { name: "Tempus Editorial" },
  },
  {
    id: "2",
    title: "Patek Philippe Nautilus: Chiếc Đồng Hồ Thay Đổi Cuộc Chơi",
    slug: "patek-philippe-nautilus-chiec-dong-ho-thay-doi-cuoc-choi",
    excerpt: "Từ bị chê bai đến biểu tượng — câu chuyện về Gerald Genta và chiếc đồng hồ sport luxury đầu tiên trong lịch sử haute horlogerie.",
    image: "https://images.unsplash.com/photo-1548171916-c8d1c1e8bc66?w=800",
    views: 8900,
    isPublished: true,
    createdAt: "2025-12-01",
    author: { name: "Tempus Editorial" },
  },
  {
    id: "3",
    title: "Hướng Dẫn Bảo Dưỡng Đồng Hồ Cơ: Giữ Gìn Giá Trị Vĩnh Cửu",
    slug: "huong-dan-bao-duong-dong-ho-co",
    excerpt: "Những bí quyết quan trọng để bảo quản đồng hồ cơ khí của bạn luôn trong tình trạng hoàn hảo — từ việc lên dây cót đến bảo dưỡng định kỳ.",
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800",
    views: 15200,
    isPublished: true,
    createdAt: "2025-12-20",
    author: { name: "Tempus Workshop" },
  },
  {
    id: "4",
    title: "Xu Hướng Đồng Hồ 2025: Sự Trở Lại Của Vàng Hồng & Mặt Số Màu",
    slug: "xu-huong-dong-ho-2025",
    excerpt: "Watches & Wonders 2025 đã khẳng định — vàng hồng, mặt số xanh lục và thiết kế retro đang thống trị thế giới đồng hồ cao cấp.",
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=800",
    views: 6700,
    isPublished: true,
    createdAt: "2026-01-10",
    author: { name: "Tempus Trends" },
  },
];
